url: http://pilz.github.io/jekyll-danskskole/
baseurl: /jekyll-danskskole/

# Site settings
title: Den Danske Skole e.V.
email: skole@dawn.dk
description: "Den Danske Skole giver mulighed for at mødes med ligesindede i hyggelige og lærerige rammer."

bestyrelse:
- name: "Sabine Jensen"
  pic: 1
  position: Formand
  social:
    - title: facebook
      url: https://www.facebook.com/profile.php?id=1194761842

- name: "Dr. Karina Bauer"
  pic: 2
  position: "Næstformand"
  social:
    - title: facebook
      url: https://www.facebook.com/profile.php?id=1194761842

- name: "Steen Skole"
  pic: 3
  position: "Kasserer"
  social:
    - title: facebook
      url: https://www.facebook.com/profile.php?id=1194761842

- name: "Kim Jensen"
  pic: 4
  position: "Sekretær & Web Administrator"
  social:
    - title: facebook
      url: https://www.facebook.com/profile.php?id=1194761842

- name: "Stine Kirkegaard"
  pic: 1
  position: "Kommunikationskonsulent"
  social:
    - title: facebook
      url: https://www.facebook.com/profile.php?id=1194761842

# Team names, titles and social links
people:
- name: "Lotte Søding Nielsen"
  pic: 1
  position: Legegruppen
  social:
    - title: facebook
      url: https://www.facebook.com/profile.php?id=1194761842

- name: Sabine Emslander
  pic: 2
  position: Første og Anden Klasse
  social:
    # - title: twitter
    #   url: #
    - title: facebook
      url: https://www.facebook.com/sabine.emslander.5?fref=ts
    # - title: linkedin
    #   url: #

- name: Birgit Bazzar
  pic: 3
  position: 4. + 5. klasse
  social:
    - title: linkedin
      url: birgit bazzar
    # - title: facebook
    #   url: #
    # - title: google-plus
    #   url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Comenius Grundschule
  - line: Kaflerstraße 14
  - line: 81241 München (Pasing)

# Build settings
markdown: kramdown
permalink: pretty
