url: http://www.dansk-skole.de
baseurl: 

# Site settings
title: Den Danske Skole e.V.
email: skole@dawn.dk
description: "Den Danske Skole giver mulighed for at mødes med ligesindede i hyggelige og lærerige rammer."

bestyrelse:
- name: "Karina Kjær"
  pic: 2
  position: Formand
  social:
    - title: facebook
      url: https://www.facebook.com/profile.php?id=540891956

- name: "Stine Kirkegaard"
  pic: 5
  position: "Næstformand"
  social:
    - title: facebook
      url: https://www.facebook.com/stine.h.kirkegaard

- name: "Steen Skole"
  pic: 3
  position: "Kasserer"
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/steen-skole-a361799

- name: "Bolette Borksand"
  pic: 6
  position: "Sekretær"
  social:
    - title: facebook
      url: https://www.facebook.com/DanishDynamite

- name: "Mikkel Tøttrup"
  pic: 7
  position: "Ungdomsofficer"
  social:
    - title: facebook
      url: https://www.facebook.com/mikkel.toettrup



# Team names, titles and social links
people:
- name: "Lotte Sødring Nielsen"
  pic: 1
  position: Lærer for Legegruppen
  social:
    - title: facebook
      url: https://www.facebook.com/profile.php?id=1194761842

- name: Sophie-Amalie Munch
  pic: 5
  position: Vikar
  social:
    # - title: linkedin
    #   url: birgit bazzar
    - title: facebook
      url: https://www.facebook.com/sophieamalie.munch.9
    # - title: google-plus
    #   url: #

- name: "Mikkel Tøttrup"
  pic: 15
  position: "Hjælpelærer for legegruppen"
  social:
    - title: facebook
      url: https://www.facebook.com/mikkel.toettrup

- name: Maiken Bertelsen
  pic: 4
  position: Lærer for 0. + 1. klasse
  social:
    # - title: linkedin
    #   url: birgit bazzar
    - title: facebook
      url: https://www.facebook.com/maiken.bertelsen.1
    # - title: google-plus
    #   url: #

- name: Nana Arnfred
  pic: 6
  position: Lærer for 2. + 3. klasse 
  social:
    # - title: linkedin
    #   url: birgit bazzar
    - title: facebook
      url: https://www.facebook.com/NSMA2206
    # - title: google-plus
    #   url: #


- name: Sabine Emslander
  pic: 2
  position: Lærer for 0. + 1. klasse
  social:
    # - title: twitter
    #   url: #
    - title: facebook
      url: https://www.facebook.com/sabine.emslander.5?fref=ts
    # - title: linkedin
    #   url: #

- name: Cheri Isen
  pic: 11
  position: Vikar
  social:
    # - title: linkedin
    #   url: birgit bazzar
    - title: facebook
      url: https://www.facebook.com/cheri.isen?fref=ts
    # - title: google-plus
    #   url: #

- name: Rune Stefansson
  pic: 13
  position: Lærer for 4. + 5. klasse
  social:
    # - title: linkedin
    #   url: birgit bazzar
    - title: facebook
      url: https://www.facebook.com/rune.stefansson
    # - title: google-plus
    #   url: #

- name: Rune Krüger
  pic: 14
  position: Duke of Edinburgh Award deltager
  social:
    # - title: linkedin
    #   url: birgit bazzar
    - title: facebook
      url: https://www.facebook.com/rune.stefansson
    # - title: google-plus
    #   url: #

- name: Clara Wärme Otterstrøm
  pic: 16
  position: Hjælpelærer 0+1 klasse
  social:
    # - title: linkedin
    #   url: birgit bazzar
    - title: facebook
      url: https://www.facebook.com/profile.php?id=1483013939
    # - title: google-plus
    #   url: #

- name: Katrine Holmsnæs
  pic: 17
  position: Hjælpelærer 
  social:
    # - title: linkedin
    #   url: birgit bazzar
    - title: facebook
      url: https://www.facebook.com/katrine.holmsnaes
    # - title: google-plus
    #   url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/groups/368658962706/
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Comenius Grundschule
  - line: Kaflerstraße 14
  - line: 81241 München (Pasing)

# Build settings
markdown: kramdown
permalink: pretty
